"""empty message

Revision ID: afd2f49956a0
Revises: 86dc44ee2aa5
Create Date: 2024-01-11 13:25:25.884407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd2f49956a0'
down_revision: Union[str, None] = '86dc44ee2aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_fullname_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_fullname_key', 'users', ['fullname'])
    # ### end Alembic commands ###
